python main.py \
--epoch 1 \
--batch_size 16 \
--classes_num 652 \
--model "TDNN" \
--data_dir "" \
--preprocessor "sequence" \
--label_query "select * from (select family, count(*) as c from base_list group by family order by c desc) as t where t.c > 9" \
--data_query "select path, family from base_list where md5 >= 'c' order by md5" \
--data_type "db" \
--dropout_prob 1 \
--learning_rate 0.0001 \
--dataset "raw" \
--GPU "0,1,2" \
--feature_maps "[100,200,300,400,500]" \
--kernels "[2,4,6,8,10]" \
--binary_embed_width 32 \
--binary_embed_height 24000 \
--checkpoint_dir "/data/dict/refactoring/checkpoint_ccnn_0418/0/" \
--forward_only True \
--whitelist False
