python main.py \
--epoch 1 \
--batch_size 50 \
--classes_num 4 \
--model "Resnet" \
--data_dir "/data/dict/PE" \
--preprocessor "thumbnail" \
--dataset "raw" \
--checkpoint_dir "/data/dict/refactoring/checkpoint_sp2/" \
--forward_only False
--specialist True
